# Generated by Django 4.2 on 2023-04-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0007_alter_goalcategory_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardparticipant",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="board",
                to="goals.board",
                verbose_name="Доска",
            ),
        ),
    ]
