version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    volumes:
      -  todomanager_12:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 10
      interval: 3s

  api:
    image: kubmark/todolist_manager:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django_static:/todolist/static

  frontend:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    ports:
      - "8011:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static

volumes:
  todomanager_12:
  django_static: