name: Test and Build

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      VK_OAUTH2_KEY: 1234567
      VK_OAUTH2_SECRET_KEY: 'VK_OAUTH_SECRET_KEY'
    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dependancies
        run: |
          pip install "poetry==1.3.2"
          poetry config virtualenvs.create true
          poetry install -n --without dev
      - name: Run tests
        run: poetry run pytest . -v

  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.prod
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todolist_manager:${{ env.BRANCH_NAME }}
